#!/usr/bin/env node
// post-build step: generate dist/demo-standalone.html with both the compiled
// tailwind stylesheet and the umd bundle inlined, so the demo is a single file
// that works offline, from file://, with an empty network panel.
//
// run after `vite build` and `npm run build:css`.

import { readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const distDir = join(root, 'dist');

const umdPath = join(distDir, 'printcraft.umd.js');
const cssPath = join(distDir, 'demo.css');
const demoPath = join(root, 'demo', 'index.html');
const outPath = join(distDir, 'demo-standalone.html');

function read(path, hint) {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    console.error(`${path} is missing; ${hint}`);
    process.exit(1);
  }
}

/**
 * an inlined asset containing a literal closing script tag would truncate the
 * page at that point. this has bitten the project once already, through a code
 * comment, so both assets are checked rather than trusted.
 */
function assertInlineable(source, what) {
  // split deliberately: this file must not contain the sequence it checks for
  // oxlint-disable-next-line no-useless-concat
  if (source.includes('</scr' + 'ipt>')) {
    throw new Error(`${what} contains a closing script tag and cannot be inlined`);
  }
}

/**
 * tsc emits one .d.ts with an `export default`, but the two consumers need
 * different views of it:
 *
 * - `import` needs an ESM-flavoured entry, or default-import interop is ambiguous
 *   in a `type: commonjs` package.
 * - `require` needs `export =`, because the UMD bundle really does assign
 *   `module.exports = Printcraft`. Typed as a default export, TypeScript under
 *   node16 would demand a `.default` that does not exist at runtime.
 *
 * Both shims re-export the single emitted declaration file; neither duplicates it.
 */
function writeDeclarationShims() {
  const typesDir = join(distDir, 'types');
  const entry = read(join(typesDir, 'index.d.ts'), 'run `npm run build:types` first');

  writeFileSync(
    join(typesDir, 'index.d.mts'),
    '// generated by tools/build.mjs — the ESM view of the emitted declarations.\n' +
      "export * from './index.js';\n" +
      "export { default } from './index.js';\n"
  );

  // the emitted entry re-exports every public type on one line; mirror exactly
  // that list into the namespace so `export =` consumers keep them
  const match = entry.match(/export type \{([^}]+)\} from '\.\/types';/);
  if (!match) throw new Error('could not find the type re-export line in index.d.ts');
  const names = match[1]
    .split(',')
    .map((n) => n.trim())
    .filter(Boolean);
  if (!names.length) throw new Error('the type re-export line in index.d.ts is empty');

  const aliases = names.map((n) => `  export type ${n} = T.${n};`).join('\n');
  writeFileSync(
    join(typesDir, 'index.d.cts'),
    '// generated by tools/build.mjs — the CJS view of the emitted declarations.\n' +
      '// the umd bundle assigns `module.exports = Printcraft`, so these types use\n' +
      '// `export =` rather than a default export.\n' +
      "import PrintcraftClass from './index.js';\n" +
      "import type * as T from './types.js';\n\n" +
      'declare const Printcraft: typeof PrintcraftClass;\n\n' +
      'declare namespace Printcraft {\n' +
      aliases +
      '\n}\n\n' +
      'export = Printcraft;\n'
  );
}

function replaceMarked(html, marker, replacement) {
  const re = new RegExp(`<!-- ${marker} -->[\\s\\S]*?<!-- /${marker} -->`);
  if (!re.test(html)) throw new Error(`demo/index.html is missing the ${marker} markers`);
  return html.replace(re, replacement);
}

writeDeclarationShims();

const lib = read(umdPath, 'run `vite build` first').replace(/\/\/# sourceMappingURL=.*$/m, '');
const css = read(cssPath, 'run `npm run build:css` first');
assertInlineable(lib, 'the umd bundle');
assertInlineable(css, 'the compiled stylesheet');

let html = read(demoPath, 'the demo source is required');
html = replaceMarked(html, 'PRINTCRAFT:CSS', '<style>\n' + css + '\n</style>');
html = replaceMarked(html, 'PRINTCRAFT:LIB', '<script>\n' + lib + '\n</script>');

if (/<(script|link)[^>]+(src|href)=["']?(https?:)?\/\//i.test(html)) {
  throw new Error('the standalone demo still references an external url');
}

writeFileSync(outPath, html);

const kb = (f) => Math.round(statSync(f).size / 102.4) / 10;
console.log(
  `built dist/demo-standalone.html (${kb(outPath)}KB: ${kb(cssPath)}KB css + ${kb(umdPath)}KB lib, no external requests)`
);
