#!/usr/bin/env node
/* Emits the TypeScript declarations and the two entry shims around them.
 *
 * tsc produces one .d.ts with an `export default`, but the two consumers need
 * different views of it:
 *
 * - `import` needs an ESM-flavoured entry, or default-import interop is
 *   ambiguous in a `type: commonjs` package.
 * - `require` needs `export =`, because the UMD bundle really does assign
 *   `module.exports = Printcraft`. Typed as a default export, TypeScript under
 *   node16 would demand a `.default` that does not exist at runtime.
 *
 * Both shims re-export the single emitted declaration file; neither duplicates
 * it. `npm run lint:pkg` is what proves this is right.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const typesDir = join(root, 'dist', 'types');

execFileSync(join(root, 'node_modules', '.bin', 'tsc'), ['-p', 'tsconfig.types.json'], {
  cwd: root,
  stdio: 'inherit'
});

const entry = readFileSync(join(typesDir, 'index.d.ts'), 'utf8');

writeFileSync(
  join(typesDir, 'index.d.mts'),
  '// generated by tools/build-types.mjs — the ESM view of the emitted declarations.\n' +
    "export * from './index.js';\n" +
    "export { default } from './index.js';\n"
);

// the emitted entry re-exports every public type on one line; mirror exactly
// that list into the namespace so `export =` consumers keep them
const match = entry.match(/export type \{([^}]+)\} from '\.\/types';/);
if (!match) throw new Error('could not find the type re-export line in index.d.ts');

const names = match[1]
  .split(',')
  .map((n) => n.trim())
  .filter(Boolean);
if (!names.length) throw new Error('the type re-export line in index.d.ts is empty');

writeFileSync(
  join(typesDir, 'index.d.cts'),
  '// generated by tools/build-types.mjs — the CJS view of the emitted declarations.\n' +
    '// the umd bundle assigns `module.exports = Printcraft`, so these types use\n' +
    '// `export =` rather than a default export.\n' +
    "import PrintcraftClass from './index.js';\n" +
    "import type * as T from './types.js';\n\n" +
    'declare const Printcraft: typeof PrintcraftClass;\n\n' +
    'declare namespace Printcraft {\n' +
    names.map((n) => `  export type ${n} = T.${n};`).join('\n') +
    '\n}\n\n' +
    'export = Printcraft;\n'
);

console.log(
  `emitted dist/types (+ index.d.mts and index.d.cts, ${names.length} types re-exported)`
);
