// Turns Coloris's stylesheet into a module the bundle can carry.
//
// The colour picker ships its own css file. A library that told a host page to
// go and fetch it would break the one promise the standalone build makes — that
// it opens from `file://` with no network — so the css is read here and written
// as a string module the kit appends to its own sheet.
//
// Generated rather than imported with Vite's `?inline`, for two reasons: the
// package's exports map does not publish the minified file, and doing it here
// means the four themes Coloris ships can be cut down to the one we use, which
// is most of the weight.
//
//   node tools/vendor-css.mjs           write src/ui/kit/coloris-css.ts
//   node tools/vendor-css.mjs --check   fail if it is out of date

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(root, 'src/ui/kit/coloris-css.ts');

const check = process.argv.includes('--check');

// read from node_modules directly: the package's exports map publishes neither
// its package.json nor the minified stylesheet, so `require.resolve` cannot
// reach either of them
const pkgDir = join(root, 'node_modules/@melloware/coloris');
const version = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8')).version;
const raw = readFileSync(join(pkgDir, 'dist/coloris.min.css'), 'utf8');

/**
 * Drops the themes we do not use.
 *
 * Coloris ships `light`, `dark`, `polaroid`, `large` and `pill`. The kit follows
 * the host into dark mode through its own tokens and never sets a Coloris theme,
 * so only the default rules matter. Everything under a `.clr-picker.clr-<theme>`
 * selector goes.
 */
function trim(css) {
  const dropped = [];
  const kept = css.replace(/[^{}]*\.clr-(?:polaroid|large|pill)\b[^{}]*\{[^}]*\}/g, (match) => {
    dropped.push(match.length);
    return '';
  });
  return { css: kept.trim(), saved: dropped.reduce((a, b) => a + b, 0) };
}

const { css, saved } = trim(raw);

const module =
  `// GENERATED by tools/vendor-css.mjs — do not edit.\n` +
  `//\n` +
  `// Coloris ${version}, MIT, https://github.com/melloware/coloris\n` +
  `// Bundled rather than fetched so the standalone build needs no network. The\n` +
  `// polaroid, large and pill themes are stripped; the kit never sets one.\n` +
  `//\n` +
  `// Regenerate with \`npm run vendor:css\`.\n\n` +
  `export const COLORIS_CSS = ${JSON.stringify(css)};\n`;

if (check) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== module) {
    console.error(
      'src/ui/kit/coloris-css.ts is out of date with coloris ' +
        version +
        '. Run `npm run vendor:css`.'
    );
    process.exit(1);
  }
  console.log('coloris css is current (' + version + ')');
  process.exit(0);
}

writeFileSync(OUT, module);
console.log(
  'wrote src/ui/kit/coloris-css.ts — coloris ' +
    version +
    ', ' +
    css.length +
    ' bytes (' +
    saved +
    ' trimmed)'
);
